#!/usr/bin/env bash
# setup.sh — First-time project configuration.
# Reads .env and auto-generates terraform/terraform.tfvars.
# Usage: make setup  (or: bash scripts/setup.sh)
set -euo pipefail

BLUE='\033[36m'; GREEN='\033[32m'; YELLOW='\033[33m'; RED='\033[31m'; NC='\033[0m'
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

info()  { printf "${BLUE}==> %s${NC}\n" "$*"; }
ok()    { printf "${GREEN}✓ %s${NC}\n" "$*"; }
warn()  { printf "${YELLOW}⚠ %s${NC}\n" "$*"; }
error() { printf "${RED}ERROR: %s${NC}\n" "$*"; exit 1; }

# ── Step 1: Ensure .env exists ────────────────────────────────────────────────
if [ ! -f "$ROOT/.env" ]; then
  cp "$ROOT/.env.example" "$ROOT/.env"
  warn ".env created from .env.example"
  warn "Edit .env and set at minimum: PROJECT_ID and VNC_PASSWORD, then re-run 'make setup'."
  exit 0
fi
ok ".env found"

# ── Step 2: Read values from .env ────────────────────────────────────────────
get_env() {
  local key="$1" default="${2:-}"
  local val
  val=$(grep -E "^${key}=" "$ROOT/.env" 2>/dev/null | cut -d'=' -f2- | tr -d '"' | tr -d "'" | xargs)
  echo "${val:-$default}"
}

PROJECT_ID=$(get_env PROJECT_ID)
REGION=$(get_env REGION "us-central1")
ZONE=$(get_env ZONE "us-central1-a")
VM_NAME=$(get_env VM_NAME "novnc-chrome")
MACHINE_TYPE=$(get_env MACHINE_TYPE "e2-standard-2")
DISK_SIZE_GB=$(get_env DISK_SIZE_GB "50")
PREEMPTIBLE=$(get_env PREEMPTIBLE "false")
SUBNET_CIDR=$(get_env SUBNET_CIDR "10.0.0.0/24")
VNC_PASSWORD=$(get_env VNC_PASSWORD "changeme")

# ── Step 3: Validate required fields ─────────────────────────────────────────
if [ -z "$PROJECT_ID" ] || [ "$PROJECT_ID" = "your-gcp-project-id" ]; then
  error "PROJECT_ID is not set in .env — edit .env and set your GCP project ID."
fi
if [ "$VNC_PASSWORD" = "changeme" ] || [ -z "$VNC_PASSWORD" ]; then
  error "VNC_PASSWORD is still the default 'changeme'. Set a real password in .env before proceeding."
fi
if [ "${#VNC_PASSWORD}" -lt 8 ]; then
  error "VNC_PASSWORD must be at least 8 characters."
fi

# ── Step 4: Generate terraform/terraform.tfvars ───────────────────────────────
info "Generating terraform/terraform.tfvars..."
cat > "$ROOT/terraform/terraform.tfvars" <<EOF
# Auto-generated by scripts/setup.sh from .env — do not edit manually.
# To regenerate: make setup

project_id   = "$PROJECT_ID"
region       = "$REGION"
zone         = "$ZONE"
vm_name      = "$VM_NAME"
machine_type = "$MACHINE_TYPE"
disk_size_gb = $DISK_SIZE_GB
preemptible  = $PREEMPTIBLE
subnet_cidr  = "$SUBNET_CIDR"
EOF
ok "terraform/terraform.tfvars written"

# ── Step 5: Init Terraform if not already initialised ────────────────────────
if [ ! -d "$ROOT/terraform/.terraform" ]; then
  info "Running terraform init..."
  cd "$ROOT/terraform" && terraform init -upgrade
  ok "Terraform initialised"
else
  ok "Terraform already initialised"
fi

# ── Step 6: Enable GCP APIs (one-time; APIs need ~60s to propagate after enable)
# We check via gcloud rather than a flag file so this is always accurate.
info "Checking GCP API status..."
COMPUTE_ENABLED=$(gcloud services list \
  --project="$PROJECT_ID" --enabled \
  --filter="name:compute.googleapis.com" \
  --format="value(name)" 2>/dev/null || true)
IAP_ENABLED=$(gcloud services list \
  --project="$PROJECT_ID" --enabled \
  --filter="name:iap.googleapis.com" \
  --format="value(name)" 2>/dev/null || true)

if [ -n "$COMPUTE_ENABLED" ] && [ -n "$IAP_ENABLED" ]; then
  ok "GCP APIs already enabled (compute, iap)"
else
  info "Enabling GCP APIs via Terraform (this is a one-time step)..."
  cd "$ROOT/terraform" && terraform apply \
    -target='google_project_service.apis["compute.googleapis.com"]' \
    -target='google_project_service.apis["iap.googleapis.com"]' \
    -auto-approve

  # APIs are enabled but take ~60 seconds to fully propagate before
  # subsequent Terraform resources (IAM, firewall, VM) can reference them.
  printf "\n${YELLOW}Waiting 60 seconds for APIs to propagate...${NC}\n"
  for i in $(seq 60 -1 1); do
    printf "\r  %2ds remaining...  " "$i"
    sleep 1
  done
  printf "\r                         \r"
  ok "APIs propagated"
fi

printf "\n${GREEN}Setup complete!${NC}\n"
printf "Next step: ${BLUE}make deploy${NC}\n\n"
